# Generated by Django 2.1.5 on 2019-01-24 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacherId', models.CharField(max_length=32)),
                ('teacherName', models.CharField(max_length=32)),
                ('teacherTel', models.CharField(max_length=32)),
                ('teacherEmail', models.EmailField(max_length=254)),
                ('teacherFaculty', models.CharField(max_length=32)),
                ('teacherSub', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=32)),
                ('passWord', models.CharField(max_length=32)),
            ],
        ),
    ]
